[package]
name = "flow"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
tokio-tungstenite = "*"
futures-util = "0.3"
serde_json = "1.0.78"
uuid = { version = "0.8", features = ["v4"] }
log = "0.4.14"
env_logger = "0.9.0"
colored = "2"